"""Initial migration

Revision ID: d197c320608d
Revises: 
Create Date: 2025-12-26 19:35:38.597827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd197c320608d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_accounts_id'), table_name='accounts')
    op.drop_index(op.f('ix_authors_id'), table_name='authors')
    op.drop_index(op.f('ix_chats_id'), table_name='chats')
    op.drop_index(op.f('ix_posts_id'), table_name='posts')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_index(op.f('ix_communities_id'), table_name='communities')
    op.drop_index(op.f('ix_comments_id'), table_name='comments')
    op.execute('DROP TABLE IF EXISTS posts CASCADE;')
    op.execute('DROP TABLE IF EXISTS messages CASCADE;')
    op.execute('DROP TABLE IF EXISTS communities CASCADE;')
    op.execute('DROP TABLE IF EXISTS authors CASCADE;')
    op.execute('DROP TABLE IF EXISTS chats CASCADE;')
    op.execute('DROP TABLE IF EXISTS comments CASCADE;')
    op.execute('DROP TABLE IF EXISTS accounts CASCADE;')
    op.execute('DROP TABLE IF EXISTS account_to_community_subscriptions CASCADE;')
    op.execute('DROP TABLE IF EXISTS account_to_account_subscriptions CASCADE;')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('authors_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('type', postgresql.ENUM('ACCOUNT', 'COMMUNITY', name='authortype'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='authors_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_authors_id'), 'authors', ['id'], unique=False)
    op.create_table('account_to_community_subscriptions',
    sa.Column('account_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('community_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('account_to_community_subscriptions_account_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], name=op.f('account_to_community_subscriptions_community_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('account_id', 'community_id', name=op.f('account_to_community_subscriptions_pkey'))
    )
    op.create_table('accounts',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('accounts_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('avatar_url', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('subscribersAmount', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('firstName', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('lastName', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('isActive', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('stack', postgresql.ARRAY(sa.VARCHAR(length=50)), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('roles', postgresql.ARRAY(postgresql.ENUM('USER', 'ADMIN', name='roles')), autoincrement=False, nullable=True),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], name='accounts_author_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='accounts_pkey'),
    sa.UniqueConstraint('username', name='accounts_username_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_accounts_id'), 'accounts', ['id'], unique=False)
    op.create_table('communities',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('admin_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('bannerUrl', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('avatarUrl', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('subscribersAmount', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('isJoined', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('themes', postgresql.ARRAY(sa.VARCHAR(length=30)), autoincrement=False, nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.VARCHAR(length=30)), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['accounts.id'], name=op.f('communities_admin_id_fkey')),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], name=op.f('communities_author_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('communities_pkey'))
    )
    op.create_index(op.f('ix_communities_id'), 'communities', ['id'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('commentId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('postId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['accounts.id'], name=op.f('comments_author_id_fkey')),
    sa.ForeignKeyConstraint(['postId'], ['posts.id'], name=op.f('comments_postId_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('comments_pkey'))
    )
    op.create_index(op.f('ix_comments_id'), 'comments', ['id'], unique=False)
    op.create_table('account_to_account_subscriptions',
    sa.Column('subscriber_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('subscribed_to_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['subscribed_to_id'], ['accounts.id'], name=op.f('account_to_account_subscriptions_subscribed_to_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscriber_id'], ['accounts.id'], name=op.f('account_to_account_subscriptions_subscriber_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('subscriber_id', 'subscribed_to_id', name=op.f('account_to_account_subscriptions_pkey'))
    )
    op.create_table('chats',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('chats_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('userFirstId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('userSecondId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['userFirstId'], ['accounts.id'], name='chats_userFirstId_fkey'),
    sa.ForeignKeyConstraint(['userSecondId'], ['accounts.id'], name='chats_userSecondId_fkey'),
    sa.PrimaryKeyConstraint('id', name='chats_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_chats_id'), 'chats', ['id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('userFromId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('personalChatId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('isRead', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('chatId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chatId'], ['chats.id'], name=op.f('messages_chatId_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('messages_pkey'))
    )
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_table('posts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('content', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.Column('author_type', postgresql.ENUM('ACCOUNT', 'COMMUNITY', name='authortype'), autoincrement=False, nullable=False),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('images', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('likes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('likes_users', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], name=op.f('posts_author_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('posts_pkey'))
    )
    op.create_index(op.f('ix_posts_id'), 'posts', ['id'], unique=False)
    # ### end Alembic commands ###
